version: '3.4'

services:
  learning:
    image: ${DOCKER_REGISTRY-}learning
    build:
      context: .
      dockerfile: Learning/Dockerfile
    ports:
       - "5000:5000"
       - "5001:5001"
  learning.db:
     image: mcr.microsoft.com/mssql/server
     environment:
        SA_PASSWORD: "Password123"
        ACCEPT_EULA: "Y"
     ports:
         - "1433:1433"
     depends_on:
      - learning
